version: "3.8"

services:

  postgres:
    image: "postgres:14"
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
